spring:
  application:
    name: service-turbine
server:
  port: 8769
turbine:
  aggregator:
    cluster-config: default
  app-config: eureka-ribbon-client, eureka-feign-client
  cluster-name-expression: new String("default")
  combine-host-port: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"